import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Sidebar from "@/src/components/Sidebar/Sidebar";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main data-test className={styles.main}>
        <p>Hello</p>
        <div>Vet a la verga </div>
        <h6 className="vete ">ERES E LAM</h6>
        <p>Hello</p>
        <div>Vet a la verga </div>
        <h6 className="vete ">ERES E LAM</h6>
        <p>Hello</p>
        <div>Vet a la verga </div>
        <h6 className="vete ">ERES E LAM</h6>
        <p>Hello</p>
        <div>Vet a la verga </div>
        <h6 className="vete ">ERES E LAM</h6>
        <p>Hello</p>
        <div>Vet a la verga </div>
        <h6 className="vete ">ERES E LAM</h6>
      </main>
    </>
  );
}
